// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/admin.proto

/*
Package admin is a generated protocol buffer package.

It is generated from these files:
	proto/admin.proto

It has these top-level messages:
	ConfigurationRequest
	ConfigurationResponse
	StatisticsRequest
	StatisticsResponse
	StatisticsConsolidation
	Metric
*/
package admin

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfigurationResponse_Extension int32

const (
	ConfigurationResponse_YAML ConfigurationResponse_Extension = 0
)

var ConfigurationResponse_Extension_name = map[int32]string{
	0: "YAML",
}
var ConfigurationResponse_Extension_value = map[string]int32{
	"YAML": 0,
}

func (x ConfigurationResponse_Extension) String() string {
	return proto.EnumName(ConfigurationResponse_Extension_name, int32(x))
}
func (ConfigurationResponse_Extension) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

type ConfigurationRequest struct {
}

func (m *ConfigurationRequest) Reset()                    { *m = ConfigurationRequest{} }
func (m *ConfigurationRequest) String() string            { return proto.CompactTextString(m) }
func (*ConfigurationRequest) ProtoMessage()               {}
func (*ConfigurationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ConfigurationResponse struct {
	Content   string                          `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Extension ConfigurationResponse_Extension `protobuf:"varint,2,opt,name=extension,enum=google.pubsub.kafka.emulator.ConfigurationResponse_Extension" json:"extension,omitempty"`
}

func (m *ConfigurationResponse) Reset()                    { *m = ConfigurationResponse{} }
func (m *ConfigurationResponse) String() string            { return proto.CompactTextString(m) }
func (*ConfigurationResponse) ProtoMessage()               {}
func (*ConfigurationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ConfigurationResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ConfigurationResponse) GetExtension() ConfigurationResponse_Extension {
	if m != nil {
		return m.Extension
	}
	return ConfigurationResponse_YAML
}

type StatisticsRequest struct {
}

func (m *StatisticsRequest) Reset()                    { *m = StatisticsRequest{} }
func (m *StatisticsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatisticsRequest) ProtoMessage()               {}
func (*StatisticsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StatisticsResponse struct {
	PublisherExecutors  int32                               `protobuf:"varint,1,opt,name=publisherExecutors" json:"publisherExecutors,omitempty"`
	SubscriberExecutors int32                               `protobuf:"varint,2,opt,name=subscriberExecutors" json:"subscriberExecutors,omitempty"`
	PublisherByTopic    map[string]*StatisticsConsolidation `protobuf:"bytes,3,rep,name=publisherByTopic" json:"publisherByTopic,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SubscriberByTopic   map[string]*StatisticsConsolidation `protobuf:"bytes,4,rep,name=subscriberByTopic" json:"subscriberByTopic,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StatisticsResponse) Reset()                    { *m = StatisticsResponse{} }
func (m *StatisticsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatisticsResponse) ProtoMessage()               {}
func (*StatisticsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StatisticsResponse) GetPublisherExecutors() int32 {
	if m != nil {
		return m.PublisherExecutors
	}
	return 0
}

func (m *StatisticsResponse) GetSubscriberExecutors() int32 {
	if m != nil {
		return m.SubscriberExecutors
	}
	return 0
}

func (m *StatisticsResponse) GetPublisherByTopic() map[string]*StatisticsConsolidation {
	if m != nil {
		return m.PublisherByTopic
	}
	return nil
}

func (m *StatisticsResponse) GetSubscriberByTopic() map[string]*StatisticsConsolidation {
	if m != nil {
		return m.SubscriberByTopic
	}
	return nil
}

type StatisticsConsolidation struct {
	Metrics []*Metric `protobuf:"bytes,1,rep,name=metrics" json:"metrics,omitempty"`
}

func (m *StatisticsConsolidation) Reset()                    { *m = StatisticsConsolidation{} }
func (m *StatisticsConsolidation) String() string            { return proto.CompactTextString(m) }
func (*StatisticsConsolidation) ProtoMessage()               {}
func (*StatisticsConsolidation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StatisticsConsolidation) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metric struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Value       string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Metric) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfigurationRequest)(nil), "google.pubsub.kafka.emulator.ConfigurationRequest")
	proto.RegisterType((*ConfigurationResponse)(nil), "google.pubsub.kafka.emulator.ConfigurationResponse")
	proto.RegisterType((*StatisticsRequest)(nil), "google.pubsub.kafka.emulator.StatisticsRequest")
	proto.RegisterType((*StatisticsResponse)(nil), "google.pubsub.kafka.emulator.StatisticsResponse")
	proto.RegisterType((*StatisticsConsolidation)(nil), "google.pubsub.kafka.emulator.StatisticsConsolidation")
	proto.RegisterType((*Metric)(nil), "google.pubsub.kafka.emulator.Metric")
	proto.RegisterEnum("google.pubsub.kafka.emulator.ConfigurationResponse_Extension", ConfigurationResponse_Extension_name, ConfigurationResponse_Extension_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Admin service

type AdminClient interface {
	// Checks metrics from pub/sub emulator
	Statistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsResponse, error)
	// Get current configuration of pub/sub emulator
	Configuration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationResponse, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) Statistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsResponse, error) {
	out := new(StatisticsResponse)
	err := grpc.Invoke(ctx, "/google.pubsub.kafka.emulator.Admin/Statistics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) Configuration(ctx context.Context, in *ConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationResponse, error) {
	out := new(ConfigurationResponse)
	err := grpc.Invoke(ctx, "/google.pubsub.kafka.emulator.Admin/Configuration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Admin service

type AdminServer interface {
	// Checks metrics from pub/sub emulator
	Statistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error)
	// Get current configuration of pub/sub emulator
	Configuration(context.Context, *ConfigurationRequest) (*ConfigurationResponse, error)
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_Statistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Statistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.pubsub.kafka.emulator.Admin/Statistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Statistics(ctx, req.(*StatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_Configuration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Configuration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/google.pubsub.kafka.emulator.Admin/Configuration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Configuration(ctx, req.(*ConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "google.pubsub.kafka.emulator.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Statistics",
			Handler:    _Admin_Statistics_Handler,
		},
		{
			MethodName: "Configuration",
			Handler:    _Admin_Configuration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/admin.proto",
}

func init() { proto.RegisterFile("proto/admin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 593 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0x7f, 0xce, 0x9f, 0xf6, 0x97, 0x89, 0x40, 0xc9, 0x36, 0x49, 0x43, 0x54, 0x89, 0xc8,
	0xe2, 0x90, 0x0b, 0x76, 0x9b, 0x0a, 0x09, 0x81, 0x40, 0x6a, 0x4a, 0xe0, 0x00, 0x95, 0x22, 0xb7,
	0x97, 0xc2, 0x69, 0xed, 0x6c, 0xcd, 0x2a, 0xf6, 0xae, 0xd9, 0x5d, 0x47, 0x0d, 0xdc, 0xe0, 0xcc,
	0x89, 0x13, 0x0f, 0xc0, 0x13, 0xf0, 0x28, 0xdc, 0x38, 0xf3, 0x20, 0xc8, 0xeb, 0xb8, 0x49, 0x93,
	0x10, 0x35, 0x1c, 0xb8, 0x6d, 0x66, 0x76, 0xbe, 0xdf, 0xcf, 0x6c, 0xc6, 0x03, 0xd5, 0x48, 0x70,
	0xc5, 0x6d, 0x3c, 0x0c, 0x29, 0xb3, 0xf4, 0x19, 0xed, 0xf9, 0x9c, 0xfb, 0x01, 0xb1, 0xa2, 0xd8,
	0x95, 0xb1, 0x6b, 0x8d, 0xf0, 0xc5, 0x08, 0x5b, 0x24, 0x8c, 0x03, 0xac, 0xb8, 0x68, 0x4d, 0xb3,
	0x36, 0x8e, 0xa8, 0x8d, 0x19, 0xe3, 0x0a, 0x2b, 0xca, 0x99, 0x4c, 0x6b, 0xcd, 0x06, 0xd4, 0x8e,
	0x39, 0xbb, 0xa0, 0x7e, 0x2c, 0x74, 0xdc, 0x21, 0xef, 0x62, 0x22, 0x95, 0xf9, 0xcd, 0x80, 0xfa,
	0x42, 0x42, 0x46, 0x9c, 0x49, 0x82, 0x9a, 0xb0, 0xed, 0x71, 0xa6, 0x08, 0x53, 0x4d, 0xa3, 0x6d,
	0x74, 0x4a, 0x4e, 0xf6, 0x13, 0xbd, 0x81, 0x12, 0xb9, 0x54, 0x84, 0x49, 0xca, 0x59, 0x33, 0xd7,
	0x36, 0x3a, 0xb7, 0xbb, 0x4f, 0xac, 0x75, 0x6c, 0xd6, 0x4a, 0x07, 0xab, 0x9f, 0x89, 0x38, 0x33,
	0x3d, 0xb3, 0x0e, 0xa5, 0xab, 0x38, 0xfa, 0x1f, 0x0a, 0xe7, 0x47, 0x27, 0xaf, 0x2a, 0xff, 0x99,
	0x3b, 0x50, 0x3d, 0x4d, 0x3a, 0x92, 0x8a, 0x7a, 0x32, 0x83, 0xff, 0x59, 0x00, 0x34, 0x1f, 0x9d,
	0x92, 0x5b, 0x80, 0xa2, 0xd8, 0x0d, 0xa8, 0x7c, 0x4b, 0x44, 0xff, 0x92, 0x78, 0xb1, 0xe2, 0x42,
	0xea, 0x26, 0x8a, 0xce, 0x8a, 0x0c, 0xda, 0x87, 0x1d, 0x19, 0xbb, 0xd2, 0x13, 0xd4, 0x9d, 0x2f,
	0xc8, 0xe9, 0x82, 0x55, 0x29, 0x24, 0xa0, 0x72, 0xa5, 0xd3, 0x9b, 0x9c, 0xf1, 0x88, 0x7a, 0xcd,
	0x7c, 0x3b, 0xdf, 0x29, 0x77, 0x9f, 0xaf, 0x7f, 0x88, 0x65, 0x5a, 0x6b, 0xb0, 0x20, 0xd4, 0x67,
	0x4a, 0x4c, 0x9c, 0x25, 0x7d, 0x14, 0x43, 0x75, 0x86, 0x92, 0x99, 0x16, 0xb4, 0xe9, 0x8b, 0x8d,
	0x4d, 0x4f, 0x17, 0x95, 0x52, 0xd7, 0x65, 0x87, 0xd6, 0x7b, 0xa8, 0xaf, 0x24, 0x44, 0x15, 0xc8,
	0x8f, 0xc8, 0x64, 0x3a, 0x1b, 0xc9, 0x11, 0xbd, 0x84, 0xe2, 0x18, 0x07, 0x31, 0xd1, 0x2f, 0x57,
	0xee, 0x3e, 0xb8, 0x29, 0xd5, 0x31, 0x67, 0x92, 0x07, 0x74, 0x98, 0x4e, 0x47, 0xaa, 0xf1, 0x28,
	0xf7, 0xd0, 0x68, 0x7d, 0x80, 0xc6, 0x6a, 0xd0, 0x7f, 0x60, 0x6e, 0x9e, 0xc3, 0xee, 0x1f, 0x6e,
	0xa1, 0xa7, 0xb0, 0x1d, 0x12, 0x25, 0xa8, 0x97, 0x4c, 0x55, 0xf2, 0x07, 0xdc, 0x5b, 0xef, 0x76,
	0xa2, 0x2f, 0x3b, 0x59, 0x91, 0x79, 0x06, 0x5b, 0x69, 0x08, 0x21, 0x28, 0x30, 0x1c, 0x92, 0x69,
	0x23, 0xfa, 0x8c, 0xda, 0x50, 0x1e, 0x92, 0xa4, 0xe9, 0x48, 0x65, 0x1f, 0x58, 0xc9, 0x99, 0x0f,
	0xa1, 0x5a, 0xd6, 0x6b, 0x5e, 0xe7, 0xd2, 0x1f, 0xdd, 0xef, 0x39, 0x28, 0x1e, 0x25, 0xeb, 0x02,
	0x7d, 0x36, 0x00, 0x66, 0xec, 0xc8, 0xbe, 0xf9, 0x78, 0xe8, 0xef, 0xaa, 0xb5, 0xbf, 0xe9, 0x3c,
	0x99, 0x7b, 0x1f, 0x7f, 0xfc, 0xfa, 0x92, 0x6b, 0xa0, 0x9a, 0x3d, 0x3e, 0x48, 0x77, 0x96, 0x2d,
	0x67, 0x00, 0x5f, 0x0d, 0xb8, 0x75, 0x6d, 0x05, 0xa0, 0xee, 0x46, 0xfb, 0x22, 0xa5, 0x3a, 0xfc,
	0x8b, 0x1d, 0x63, 0xde, 0xd5, 0x60, 0x77, 0xd0, 0xee, 0x0c, 0xcc, 0x9b, 0xbf, 0xd8, 0xfb, 0x64,
	0xc0, 0x7d, 0x8f, 0x87, 0x99, 0xb6, 0x17, 0xf0, 0x78, 0x68, 0x45, 0x58, 0x28, 0x46, 0x84, 0xbc,
	0x6e, 0xe5, 0xf1, 0x30, 0xe4, 0xac, 0x07, 0xfa, 0x91, 0x07, 0xc9, 0x5a, 0x1d, 0x18, 0xaf, 0x9f,
	0x4d, 0x0b, 0x7d, 0x1e, 0x60, 0xe6, 0x5b, 0x5c, 0xf8, 0xb6, 0x4f, 0x58, 0xba, 0xbc, 0xd3, 0x14,
	0x8e, 0xa8, 0xb4, 0x53, 0x21, 0x5b, 0x0b, 0xd9, 0x19, 0xb3, 0x3d, 0x3e, 0x78, 0xac, 0x99, 0xdc,
	0x2d, 0x5d, 0x70, 0xf8, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc5, 0xf5, 0x35, 0x1e, 0xf6, 0x05, 0x00,
	0x00,
}
