package com.google.cloud.partners.pubsub.kafka.integration.util;

final class Configurations {

  static final String SERVER_CONFIG_JSON =
      "{\n"
          + "  \"port\": 8080,\n"
          + "  \"kafka\": {\n"
          + "    \"bootstrapServers\": [\"localhost:9094\", \"localhost:9095\", \"localhost:9096\"],\n"
          + "    \"producerProperties\": {\n"
          + "      \"linger.ms\": \"5\",\n"
          + "      \"batch.size\": \"1000000\",\n"
          + "      \"buffer.memory\": \"32000000\"\n"
          + "    },\n"
          + "    \"producerExecutors\": 4,\n"
          + "    \"consumerProperties\": {\n"
          + "      \"max.poll.records\": \"1000\"\n"
          + "    },\n"
          + "    \"consumersPerSubscription\": 4\n"
          + "  }\n"
          + "}";

  static final String SSL_SERVER_CONFIG_JSON =
      "{\n"
          + "  \"port\": 8080,\n"
          + "  \"security\": {\n"
          + "    \"certificateChainFile\": \"/path/to/server.crt\",\n"
          + "    \"privateKeyFile\": \"/path/to/server.key\"\n"
          + "  },\n"
          + "  \"kafka\": {\n"
          + "    \"bootstrapServers\": [\"localhost:9094\", \"localhost:9095\", \"localhost:9096\"],\n"
          + "    \"producerProperties\": {\n"
          + "      \"linger.ms\": \"5\",\n"
          + "      \"batch.size\": \"1000000\",\n"
          + "      \"buffer.memory\": \"32000000\"\n"
          + "    },\n"
          + "    \"producerExecutors\": 4,\n"
          + "    \"consumerProperties\": {\n"
          + "      \"max.poll.records\": \"1000\"\n"
          + "    },\n"
          + "    \"consumersPerSubscription\": 4\n"
          + "  }\n"
          + "}";

  static final String PUBSUB_CONFIG_JSON =
      "{\n"
          + "   \"projects\":[\n"
          + "      {\n"
          + "         \"name\":\"emulator-testing\",\n"
          + "         \"topics\":[\n"
          + "            {\n"
          + "               \"name\":\"broker-failure\",\n"
          + "               \"kafkaTopic\":\"broker-failure\",\n"
          + "               \"subscriptions\":[\n"
          + "                  {\n"
          + "                     \"name\":\"subscription-to-broker-failure\",\n"
          + "                     \"ackDeadlineSeconds\":10\n"
          + "                  }\n"
          + "               ]\n"
          + "            },\n"
          + "            {\n"
          + "               \"name\":\"publish-and-streaming-pull\",\n"
          + "               \"kafkaTopic\":\"publish-and-streaming-pull\",\n"
          + "               \"subscriptions\":[\n"
          + "                  {\n"
          + "                     \"name\":\"subscription-to-publish-and-streaming-pull\",\n"
          + "                     \"ackDeadlineSeconds\":10\n"
          + "                  }\n"
          + "               ]\n"
          + "            },\n"
          + "            {\n"
          + "               \"name\":\"ssl-server\",\n"
          + "               \"kafkaTopic\":\"ssl-server\",\n"
          + "               \"subscriptions\":[\n"
          + "                  {\n"
          + "                     \"name\":\"subscription-to-secured-server\",\n"
          + "                     \"ackDeadlineSeconds\":10\n"
          + "                  }\n"
          + "               ]\n"
          + "            }\n"
          + "         ]\n"
          + "      }\n"
          + "   ]\n"
          + "}";
}
